In [ ]:
import numpy as np
num = np.array([10,20,30])
num
type(num)


numpy.ndarray

In [ ]:
array_1D= np.array([2,4,5,6])
array_1D
array_2D= np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]])
array_2D

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [ ]:
import numpy as np
output = np.array([[x for x in range(2, 21, 2)], [x for x in range(1, 20, 2)]])
print(output)
print(output.dtype)
print(output.ndim)
print(output.shape)
print(output.size)
print(output.itemsize)


[[ 2  4  6  8 10 12 14 16 18 20]
 [ 1  3  5  7  9 11 13 15 17 19]]
int64
2
(2, 10)
20
8


In [ ]:
import numpy as np

output = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])

print("Array:")
print(output)
print(output.max())
print(output.min())
print(output.sum())
print(output.std())
print(output.mean())
print(output.var())
print(output.mean(axis=0))
print(output.mean(axis=1))


Array:
[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
100
70
1054
8.792357792739987
87.83333333333333
77.30555555555556
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]


In [ ]:
import numpy as np
ary=np.array([[1,2,3],[4,5,6]])
ary
ary>5
ary<=5
ary==5

array([[False, False, False],
       [False,  True, False]])

In [ ]:
import numpy as np
num1= np.arange(1,6)
num1

num2= num1.view()
num2
print(id(num1))
print(id(num2))
num2[1]*=5
num1
num2

138854901840464
138854901841424


array([ 1, 10,  3,  4,  5])

In [ ]:
import numpy as np
num1= np.arange(1,6)
num1

num2= num1.copy()
num2

num2[1]*=5
num1
num2

array([ 1, 10,  3,  4,  5])

In [ ]:

score = [85, 90, 78, 92, 88]
score = np.array(score,dtype="f")

score1 = score.copy()
score1 =score1+5


print(score)
print(score1)
score=np.where(score1>85)
print(score)



[85. 90. 78. 92. 88.]
[90. 95. 83. 97. 93.]
(array([0, 1, 3, 4]),)
